# Generated by Django 3.2.23 on 2023-11-09 14:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('programmingStack', models.CharField(choices=[('Reactjs', 'Reactjs'), ('Vue', 'Vue'), ('Angular', 'Angular'), ('MySQL', 'MySQL'), ('Go', 'Go'), ('PHP', 'PHP'), ('Java', 'Java'), ('Microsoft SQL Server', 'Microsoft SQL Server'), ('SQL', 'SQL'), ('Postgres', 'Postgres')], max_length=20)),
                ('upload', models.FileField(default='', upload_to='uploads/files', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('programming_stack', models.CharField(max_length=20)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='uploads/certificates')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
        ),
    ]
